#!/bin/bash

json_file="./summary.json"

echo "report file: "
cat ./summary.json
# Use jq to extract the count of passed, failed, skipped tests
passed=$(jq '.passed | length' "$json_file")
failed=$(jq '.failed | length' "$json_file")
skipped=$(jq '.skipped | length' "$json_file")

# Calculate the total count
total=$((passed + failed + skipped))

# Pass the resuls to the env variables
echo "passed=$passed" >> $GITHUB_ENV
echo "failed=$failed" >> $GITHUB_ENV
echo "skipped=$skipped" >> $GITHUB_ENV
echo "total=$total" >> $GITHUB_ENV
