export enum ExpertsLinkedInLinks {
	IvanIeremenko = 'https://www.linkedin.com/in/ivan-ieremenko/',
	OleksiiSvystun = 'https://www.linkedin.com/in/alexsvystun/',
	IvanYeremenko = 'https://www.linkedin.com/in/ivan-yeremenko-a464125a/',
	YevheniiKarachevtsev = 'https://www.linkedin.com/in/yevhenii-karachevtsev-372749236/',
	VitaliiDolotov = 'https://www.linkedin.com/in/vitaliidoltov/',
	DmytroDytiuk = 'https://www.linkedin.com/in/dmytrodytiuk/',
	DmytroShtapauk = 'https://www.linkedin.com/in/dmytroshtapauk/',
	DmytroGamanenko = 'https://www.linkedin.com/in/dgamanenko/',
	MariaDarmanian = 'https://www.linkedin.com/in/maria-darmanian-8349458a/',
	OleksandrBezrukov = 'https://www.linkedin.com/in/oleksandr-bezrukov-568852213/',
	VladyslavUshakov = 'https://www.linkedin.com/in/vladyslav-ushakov-086924124/',
	HannaZhyhan = 'https://www.linkedin.com/in/hanna-zhygan-8a2158234/',
	YelyzavetaLvova = 'https://www.linkedin.com/in/yelyzaveta-lvova-b6b6b5199/',
	MaxLevytskyi = 'https://www.linkedin.com/in/maxlevitskiy/',
	ArtemDolotov = 'https://www.linkedin.com/in/artemdolotov/',
	NastasiiaDudnik = 'https://www.linkedin.com/in/nastasia-dudnik/',
	KyryloMasiuk = 'https://www.linkedin.com/in/kyrylo-masiuk-9b424a93/',
	AndriiDumych = 'https://www.linkedin.com/in/andrii-dumych-10b945171/',
	SerhiiYevdokymenko = 'https://www.linkedin.com/in/devops-yevdokymenko/',
	DmytroPakki = 'https://www.linkedin.com/in/dmytro-pakki-530406161/',
	SerhiiLedniov = 'https://www.linkedin.com/in/serhii-lednov/',
	OleksandrMakarov = 'https://www.linkedin.com/in/oleksamakarov/',
	DmitryValko = 'https://www.linkedin.com/in/dima-valko/',
	MariiaPetrovych = 'https://www.linkedin.com/in/mpetrovych/',
}
