export enum ExpertNames {
	OleksiiSvystun = 'Oleksii Svystun',
	YevheniiKarachevtsev = 'Yevhenii Karachevtsev',
	OleksandrBezrukov = 'Oleksandr Bezrukov',
	IvanYeremenko = 'Ivan Yeremenko',
	IvanIeremenko = 'Ivan Ieremenko',
	VitaliiDolotov = 'Vitalii Dolotov',
	DmytroDytiuk = 'Dmytro Dytiuk',
	DmytroShtapauk = 'Dmytro Shtapauk',
	MariaDarmanian = 'Maria Darmanian',
	YuliaMelnychenko = 'Yulia Melnychenko',
	ElizabethMalygina = 'Elizabeth Malygina',
	HannaZhyhan = 'Hanna Zhyhan',
	VladyslavUshakov = 'Vladyslav Ushakov',
	YelyzavetaLvova = 'Yelyzaveta Lvova',
}
