export enum ExpertiseEnum {
	CloudDev,
	DevOpsAsAServ,
	InternetOfThings,
	DigitalTransform,
	UiUxDesign,
	MobileDev,
	FrontEndDevelopment,
	BackEndDevelopment,
	BigData,
	AiDevelopment,
	ComputerVision,
	OpenAI,
	DeepLearning,
}
