export enum ExpertiseEnum {
	CloudDev,
	CloudOptimization,
	CloudModernization,
	DevOpsAsAServ,
	InternetOfThings,
	DigitalTransform,
	UiUxDesign,
	MobileDev,
	FrontEndDevelopment,
	BackEndDevelopment,
	BigData,
	AiDevelopment,
	ComputerVision,
	OpenAI,
	DeepLearning,
	AiChatbotDev,
}
