export enum ServicesEnum {
	OurServices,
	CustomDev,
	DigitalTransform,
	CloudDev,
	MobileDev,
	FrontEndDevelopment,
	BackEndDevelopment,
	BigData,
	InternetOfThings,
	DevOpsAsAServ,
	AiDevelopment,
	UiUxDesign,
	QaAsAServ,
	ConsultingServ,
}
