name: Run Unit Tests on Pull Requests

on:
  pull_request:
    branches:
      - main # Replace with the branch you want to test pull requests against

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      -name: show path
        run: pwd

      - name: Move to tests folder
        run: cd ui_tests_playwright

      - name: Run Unit Tests
        run: npm run unit-tests
